#! /usr/bin/env bash
#------------------------------------------------------------------------------
#
# lsmount   Show a clean list of block device mounts.
#
# Version:  0.0.0
#
# Copyright (C) 2023 Toni Homedes i Saun <toni@homedes.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#------------------------------------------------------------------------------

mount | grep -E "^($(lsblk -o PATH | tail +2 | sed 's/\//\\\//g' | paste -sd '|'))\s"
